// wdio.conf.js — WebdriverIO (WDIO) configuration
// Auto-generated by TestQ.
// Set BASE_URL env var to point at your application under test.
// Set CI=true to run headless in CI/CD pipelines.

exports.config = {
  runner: 'local',

  // Test files — one spec per scenario, grouped under test/specs/{pbi-id}/
  specs: ['./test/specs/**/*.test.js'],
  exclude: [],

  maxInstances: 1,

  // wdio-chromedriver-service auto-starts ChromeDriver before tests run.
  // No manual driver download or PATH setup needed — just npm install && npm test.
  services: ['chromedriver'],

  capabilities: [{
    maxInstances: 1,
    browserName: 'chrome',
    acceptInsecureCerts: true,
    // Run headless automatically in CI environments
    'goog:chromeOptions': {
      args: process.env.CI
        ? ['--headless', '--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu']
        : [],
    },
  }],

  logLevel: 'warn',
  bail: 0,
  baseUrl: process.env.BASE_URL || 'http://localhost:3000',
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,

  framework: 'mocha',

  reporters: ['spec'],

  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
    // @babel/register lets test files use either import/export or require() —
    // so AI-generated code works regardless of which module syntax it uses.
    require: ['@babel/register'],
  },
};
